import { TArrayOfUsers } from "./types";

export const usersArray:TArrayOfUsers = [
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    },
    {
        name:"Peter",
        secondName:"Ivanov",
        gender:"М",
        age:12,
        rank:17 
    },
    {
        name:"Kate",
        secondName:"Zagagunnaja",
        gender:"ж",
        age:55,
        rank:100
    },
    {
        name:"Игорь",
        secondName:"Власевич",
        gender:"М",
        age:14,
        rank:80 
    },
    {
        name:"Коля",
        secondName:"Айвазов",
        gender:"М",
        age:19,
        rank:51 
    },
    {
        name:"Яна",
        secondName:"Пруткина",
        gender:"ж",
        age:8,
        rank:78
    },
    {
        name:"Vasja",
        secondName:"Petrov",
        gender:"М",
        age:10,
        rank:82 
    }
]